services:
  - type: web
    name: clazify-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GOOGLE_SHEET_ID
        sync: false
